name: Sync Midgard Technical Spec

on:
  schedule:
    - cron: '0 5 * * *'  # Every day at 05:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install diffutils and rsync
        run: sudo apt-get update && sudo apt-get install -y diffutils rsync

      - name: Clone Midgard repo
        run: git clone https://github.com/Anastasia-Labs/midgard.git midgard-latest

      - name: Backup current technical-spec
        run: |
          mkdir -p temp-backup
          cp -r technical-spec/* temp-backup/ || true

      - name: Sync midgard/technical-spec to local technical-spec
        run: |
          rsync -av --delete --exclude '.git' midgard-latest/technical-spec/ technical-spec/ > sync-log.txt

      - name: Show changed files
        run: |
          echo "==== Changed Files ===="
          diff -qr temp-backup/ technical-spec/ || echo "No changes found."

      - name: Commit and push if changes occurred
        run: |
          if ! git diff --quiet; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add technical-spec/
            git commit -m "Daily sync from Midgard upstream"
            git push
          else
            echo "No changes to commit."
          fi
